### ISSUE TITLE
sample of index and json input from header

### ISSUE THREAD

**Issue by kurthorvath** [inventid/gennie#11]
hi i just found your project and like the idea a lot, but actually it is not very clear to me how to input data

ok, i define a index.html file in documents directory as a template

then somehow my my request-body contain variables which are mapped.
But how do these variables look like in the **request** and the **template**?
is there a concept of arrays supported? If yes how do i adress that? i actually plan to use your project to generate invoices.

\br

K

**Comment by joostverdoorn** [comment]
Hey there!

To push data to gennie, you should POST it as json. From your template, there are two ways to get this data. 
1. You can load `/data` as javascript from your index.html: `<script src="/data"></script>` Your data will then be available as the global variable `data`.
2. You can fetch `/data.json`, which returns your data as you posted it.

Note that if you are doing asynchronous operations in your template, you need to tell the render server. This can be done by first calling `/defer`, and calling `/done` when you're done rendering in your template.
